# -*- coding: utf-8 -*-
"""MIT2019100_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jcAhean2N61mCg7Gz7dx1ZWtKqGg4zTJ
"""

import numpy as np

import matplotlib.pyplot as plt
import cv2
img = cv2.imread("/content/sample_data/iiita2.jpg")
plt.imshow(img)
plt.show()

h = img.shape[1]
h1 = h//3
h2 = 2*h1
h3 = 3*h1
img[ : , 0:h1, 2] = 255
img[ : , h1:h2, 1] = 255
img[ : , h2:h3, 0] = 255
plt.imshow(img)
plt.show()

cv2.imwrite('iiita2_channel_mit2019100.jpg',img)

