# -*- coding: utf-8 -*-
"""MIT2019100_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t5PmH0SIx7Eo3hDiP6uClJ89VZiFfVbd
"""

import numpy as np

import matplotlib.pyplot as plt
import cv2

img = cv2.imread('/content/sample_data/round.jpeg')
gray = cv2.cvtColor(img.copy(), cv2.COLOR_BGR2GRAY)
retval, thresholded = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
medianFiltered = cv2.medianBlur(thresholded,5)
cnts, hierarchy = cv2.findContours(medianFiltered, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
n = 00
a = n % 255
b = (2 * n)% 255
cd = (3 * n)% 255
cv2.drawContours(img, cnts, -1, (a, b, cd), -1)

plt.imshow(img)
plt.show()

cv2.imwrite('/content/sample_data/MIT2019100_3.jpg', img)

